function cv_refit_predict
% Smoke the CV->REFIT->PREDICT wrapper and its native JSON outcome.
if ispc
    return;
end
work = [tempname(), ' cv replay ''test'''];
mkdir(work);
cleanup = onCleanup(@() rmdir(work, 's')); %#ok<NASGU>
input = fullfile(work, 'input ''contract''.json');
writeText(input, '{}');
cli = fullfile(work, 'fake cli');
lines = { ...
    '#!/bin/sh', 'set -eu', ...
    'test "$1" = run-process-dsl-cv-refit-replay || exit 11; shift', ...
    'output=; metric=; scheduler=; gpu=0; workers=; timeout=; retries=', ...
    'while test "$#" -gt 0; do', ...
    '  case "$1" in', ...
    '    --dsl|--controllers|--envelope|--adapter|--selections) test -f "$2" || exit 12; shift 2 ;;', ...
    '    --output) output=$2; shift 2 ;;', ...
    '    --selection-metric) metric=$2; shift 2 ;;', ...
    '    --scheduler) scheduler=$2; shift 2 ;;', ...
    '    --gpu-device) gpu=$((gpu + 1)); shift 2 ;;', ...
    '    --process-workers) workers=$2; shift 2 ;;', ...
    '    --process-timeout-ms) timeout=$2; shift 2 ;;', ...
    '    --process-retries) retries=$2; shift 2 ;;', ...
    '    --bundle-id|--variant-id|--plan-id|--run-id|--root-seed|--scheduler-workers|--cpu-threads) shift 2 ;;', ...
    '    *) exit 13 ;;', ...
    '  esac', 'done', ...
    'test "$metric" = balanced_accuracy || exit 14', ...
    'test "$scheduler" = parallel || exit 15', ...
    'test "$gpu" = 1 || exit 16', ...
    'test "$workers" = 2 || exit 17', ...
    'test "$timeout" = 9000 || exit 18', ...
    'test "$retries" = 1 || exit 19', ...
    'printf ''{"bundle":{"bundle_id":"bundle:test"},"replay_node_results":[{"node_id":"model:test"}],"replay_prediction_blocks":[{"sample_ids":["s1"]}],"replay_scores":null}\n'' > "$output"' ...
};
writeText(cli, [strjoin(lines, char(10)), char(10)]);
[status, message] = system(['chmod 755 ', shellQuote(cli)]);
assert(status == 0, message);
outcome = dagml.cvRefitPredict(input, input, input, cli, ...
    'cli', cli, 'selections', input, ...
    'selectionMetric', 'balanced_accuracy', 'scheduler', 'parallel', ...
    'gpuDevices', {'0'}, 'processWorkers', 2, ...
    'processTimeoutMs', 9000, 'processRetries', 1);
assert(strcmp(outcome.bundle.bundle_id, 'bundle:test'));
assert(numel(outcome.replay_node_results) == 1);
assert(numel(outcome.replay_prediction_blocks) == 1);
try
    dagml.cvRefitPredict(input, input, input, cli, ...
        'cli', cli, 'selectionMetric', 'invalid');
    error('dagml:CvRefitPredict:Test', 'Invalid metric was not rejected.');
catch exception
    assert(strcmp(exception.identifier, 'dagml:CvRefitPredict:Option'));
end
end

function writeText(path, content)
file = fopen(path, 'w');
assert(file ~= -1);
cleanup = onCleanup(@() fclose(file)); %#ok<NASGU>
fwrite(file, content);
end

function quoted = shellQuote(value)
quote = char(39);
quoted = [quote, strrep(value, quote, [quote, '"', quote, '"', quote]), quote];
end
