function host_hpo_search
% Smoke the CLI bridge and its explicit parallel-trial boundary.
if ispc
    return;
end
work = [tempname(), ' hpo ''test'''];
mkdir(work);
cleanup = onCleanup(@() rmdir(work, 's')); %#ok<NASGU>
input = fullfile(work, 'input.json');
writeText(input, '{}');
cli = fullfile(work, 'fake cli');
writeText(cli, sprintf([ ...
    '#!/bin/sh\n' ...
    'test "$1" = run-host-hpo || exit 11\n' ...
    'shift\n' ...
    'output=\n' ...
    'parallel=\n' ...
    'persistent=0\n' ...
    'checkpoint=\n' ...
    'while test "$#" -gt 0; do\n' ...
    '  case "$1" in\n' ...
    '    --output) output=$2; shift 2 ;;\n' ...
    '    --parallel-trials) parallel=$2; shift 2 ;;\n' ...
    '    --operator-persistent) persistent=1; shift ;;\n' ...
    '    --checkpoint) checkpoint=$2; shift 2 ;;\n' ...
    '    --plan|--envelope|--request|--operator-adapter|--optimizer-adapter|--adapter-timeout-ms) shift 2 ;;\n' ...
    '    *) exit 12 ;;\n' ...
    '  esac\n' ...
    'done\n' ...
    'test "$parallel" = 1 || exit 13\n' ...
    'test "$persistent" = 1 || exit 14\n' ...
    'test -n "$checkpoint" || exit 15\n' ...
    'printf ''{"wrapper_smoke":true,"trials":[1,2]}\\n'' > "$output"\n' ...
]));
[status, message] = system(['chmod 755 ', shellQuote(cli)]);
assert(status == 0, message);
result = dagml.hostHpoSearch(input, input, input, cli, cli, ...
    'cli', cli, 'checkpoint', fullfile(work, 'checkpoint state.json'), ...
    'operatorPersistent', true);
assert(result.wrapper_smoke && numel(result.trials) == 2);
try
    dagml.hostHpoSearch(input, input, input, cli, cli, ...
        'cli', cli, 'parallelTrials', 2);
    error('dagml:HostHpo:Test', 'Parallel trials were not rejected.');
catch exception
    assert(strcmp(exception.identifier, 'dagml:HostHpo:ParallelTrials'));
end
end

function writeText(path, content)
file = fopen(path, 'w');
assert(file ~= -1);
cleanup = onCleanup(@() fclose(file)); %#ok<NASGU>
fwrite(file, content);
end

function quoted = shellQuote(value)
quote = char(39);
quoted = [quote, strrep(value, quote, [quote, '"', quote, '"', quote]), quote];
end
