function initial_full_refit
% Smoke the native no-CV REFIT capture and PREDICT replay CLI wrappers.
if ispc
    return;
end
work = [tempname(), ' refit ''test'''];
mkdir(work);
cleanup = onCleanup(@() rmdir(work, 's')); %#ok<NASGU>
input = fullfile(work, 'input ''contract''.json');
writeText(input, '{}');
cli = fullfile(work, 'fake cli');
lines = { ...
    '#!/bin/sh', 'set -eu', 'command=$1; shift', ...
    'output=; package=; workers=; timeout=; retries=; persistent=0; scheduler=; seed=; devices=0; run_id=', ...
    'while test "$#" -gt 0; do', ...
    '  case "$1" in', ...
    '    --output) output=$2; shift 2 ;;', ...
    '    --package-output) package=$2; shift 2 ;;', ...
    '    --process-workers) workers=$2; shift 2 ;;', ...
    '    --process-timeout-ms) timeout=$2; shift 2 ;;', ...
    '    --process-retries) retries=$2; shift 2 ;;', ...
    '    --persistent) persistent=1; shift ;;', ...
    '    --package-id|--plan-id|--scheduler-workers|--cpu-threads) shift 2 ;;', ...
    '    --run-id) run_id=$2; shift 2 ;;', ...
    '    --root-seed) seed=$2; shift 2 ;;', ...
    '    --scheduler) scheduler=$2; shift 2 ;;', ...
    '    --gpu-device) devices=$((devices + 1)); shift 2 ;;', ...
    '    --dsl|--controllers|--envelope|--training-sample-ids|--adapter|--package|--artifact-handles|--output-ids) test -f "$2" || exit 12; shift 2 ;;', ...
    '    *) exit 13 ;;', ...
    '  esac', 'done', ...
    'test "$workers" = 2 || exit 14', ...
    'test "$timeout" = 9000 || exit 15', ...
    'test "$retries" = 1 || exit 16', ...
    'test "$persistent" = 1 || exit 17', ...
    'case "$command" in', ...
    '  run-process-dsl-refit-phase)', ...
    '    test -n "$package" || exit 18', ...
    '    test "$scheduler" = parallel || exit 20', ...
    '    test "$seed" = 19 || exit 21', ...
    '    test "$devices" = 1 || exit 22', ...
    '    test "$run_id" = run:refit.test || exit 23', ...
    '    printf ''{"package_id":"package:test"}\n'' > "$package"', ...
    '    printf ''{"initial_full_refit_package":{"package_id":"package:test"}}\n'' > "$output" ;;', ...
    '  run-process-initial-full-refit-predict)', ...
    '    test "$run_id" = run:predict.test || exit 24', ...
    '    printf ''{"replay_outcome":{"phase":"PREDICT"}}\n'' > "$output" ;;', ...
    '  *) exit 19 ;;', ...
    'esac' ...
};
writeText(cli, [strjoin(lines, char(10)), char(10)]);
[status, message] = system(['chmod 755 ', shellQuote(cli)]);
assert(status == 0, message);
package = fullfile(work, 'signed ''package''.json');
result = dagml.initialFullRefit(input, input, input, input, cli, package, ...
    'cli', cli, 'persistent', true, 'processWorkers', 2, ...
    'processTimeoutMs', 9000, 'processRetries', 1, ...
    'rootSeed', 19, 'scheduler', 'parallel', 'gpuDevices', {'0'}, ...
    'runId', 'run:refit.test');
assert(strcmp(result.initial_full_refit_package.package_id, 'package:test'));
assert(exist(package, 'file') == 2);
replay = dagml.predictInitialFullRefit(package, input, cli, input, input, ...
    'cli', cli, 'persistent', true, 'processWorkers', 2, ...
    'processTimeoutMs', 9000, 'processRetries', 1, ...
    'runId', 'run:predict.test');
assert(strcmp(replay.replay_outcome.phase, 'PREDICT'));
try
    dagml.initialFullRefit(input, input, input, input, cli, package, ...
        'cli', cli, 'processWorkers', 0);
    error('dagml:InitialRefit:Test', 'Invalid worker count was not rejected.');
catch exception
    assert(strcmp(exception.identifier, 'dagml:InitialRefit:Option'));
end
end

function writeText(path, content)
file = fopen(path, 'w');
assert(file ~= -1);
cleanup = onCleanup(@() fclose(file)); %#ok<NASGU>
fwrite(file, content);
end

function quoted = shellQuote(value)
quote = char(39);
quoted = [quote, strrep(value, quote, [quote, '"', quote, '"', quote]), quote];
end
