function replay_bundle
% Smoke persisted bundle replay with explicit host sidecar handles.
if ispc
    return;
end
work = [tempname(), ' replay ''test'''];
mkdir(work);
cleanup = onCleanup(@() rmdir(work, 's')); %#ok<NASGU>
input = fullfile(work, 'input ''contract''.json');
writeText(input, '{}');
cli = fullfile(work, 'fake cli');
lines = { ...
    '#!/bin/sh', 'set -eu', ...
    'test "$1" = run-process-replay || exit 11; shift', ...
    'output=; envelopes=0; handles=0; workers=; timeout=; retries=', ...
    'while test "$#" -gt 0; do', ...
    '  case "$1" in', ...
    '    --graph|--campaign|--controllers|--bundle|--replay-request|--adapter|--prediction-cache-payload) test -f "$2" || exit 12; shift 2 ;;', ...
    '    --artifact-handles) test -f "$2" || exit 13; handles=$((handles + 1)); shift 2 ;;', ...
    '    --envelope) envelopes=$((envelopes + 1)); shift 2 ;;', ...
    '    --output) output=$2; shift 2 ;;', ...
    '    --process-workers) workers=$2; shift 2 ;;', ...
    '    --process-timeout-ms) timeout=$2; shift 2 ;;', ...
    '    --process-retries) retries=$2; shift 2 ;;', ...
    '    --plan-id|--run-id|--root-seed|--scheduler|--scheduler-workers|--score-output) shift 2 ;;', ...
    '    --persistent) shift ;;', ...
    '    *) exit 14 ;;', ...
    '  esac', 'done', ...
    'test "$handles" = 1 || exit 15', ...
    'test "$envelopes" = 2 || exit 16', ...
    'test "$workers" = 2 || exit 17', ...
    'test "$timeout" = 9000 || exit 18', ...
    'test "$retries" = 1 || exit 19', ...
    'printf ''{"bundle_id":"bundle:test","node_results":[{}],"prediction_blocks":[{"sample_ids":["s1"]}],"scores":null}\n'' > "$output"' ...
};
writeText(cli, [strjoin(lines, char(10)), char(10)]);
[status, message] = system(['chmod 755 ', shellQuote(cli)]);
assert(status == 0, message);
envelopes = containers.Map({'node:x', 'node:y'}, {input, input});
outcome = dagml.replayBundle(input, input, input, input, input, cli, ...
    input, envelopes, 'cli', cli, 'predictionCachePayload', input, ...
    'processWorkers', 2, 'processTimeoutMs', 9000, 'processRetries', 1);
assert(strcmp(outcome.bundle_id, 'bundle:test'));
assert(numel(outcome.prediction_blocks) == 1);
try
    dagml.replayBundle(input, input, input, input, input, cli, ...
        input, containers.Map(), 'cli', cli);
    error('dagml:ReplayBundle:Test', 'Empty envelopes were not rejected.');
catch exception
    assert(strcmp(exception.identifier, 'dagml:ReplayBundle:Envelopes'));
end
end

function writeText(path, content)
file = fopen(path, 'w');
assert(file ~= -1);
cleanup = onCleanup(@() fclose(file)); %#ok<NASGU>
fwrite(file, content);
end

function quoted = shellQuote(value)
quote = char(39);
quoted = [quote, strrep(value, quote, [quote, '"', quote, '"', quote]), quote];
end
