function run_octave_hpo_ridge_oracle()
% Exercise the public MATLAB/Octave HPO wrapper against real Octave Ridge.
addpath(fullfile(getenv('DAGML_OCTAVE_REPO'), 'bindings', 'matlab'));
result = dagml.hostHpoSearch( ...
    getenv('DAGML_OCTAVE_PLAN'), getenv('DAGML_OCTAVE_ENVELOPE'), ...
    getenv('DAGML_OCTAVE_REQUEST'), getenv('DAGML_OCTAVE_OPERATOR'), ...
    getenv('DAGML_OCTAVE_OPTIMIZER'), ...
    'cli', getenv('DAGML_OCTAVE_CLI'), ...
    'checkpoint', getenv('DAGML_OCTAVE_CHECKPOINT'), ...
    'output', getenv('DAGML_OCTAVE_OUTCOME'), ...
    'parallelTrials', 2, 'operatorPersistent', true);
assert(strcmp(char(result.status), 'completed'));
assert(numel(result.trials) >= 2);
end
