from os import PathLike
from typing import Any, Self

class DagMlError(Exception):
    category: str
    code: str
    severity: str
    remediation_hint: str
    context: dict[str, Any]
    context_json: str
    descriptor_json: str

class DagMlValidationError(DagMlError): ...
class DagMlRuntimeError(DagMlError): ...
class DagMlDataError(DagMlError): ...
class DagMlControllerError(DagMlError): ...
class DagMlBundleError(DagMlError): ...
class DagMlLineageError(DagMlError): ...
class DagMlReplayError(DagMlError): ...
class DagMlSecurityError(DagMlError): ...
class DagMlCompatibilityError(DagMlError): ...
class DagMlInternalError(DagMlError): ...

__version__: str

class JsonContract:
    def __init__(self, value: Any) -> None: ...
    @classmethod
    def from_path(cls, path: str | PathLike[str]) -> Self: ...
    def json(self) -> str: ...
    def to_dict(self) -> Any: ...

class GraphSpec(JsonContract): ...
class CampaignSpec(JsonContract): ...
class ControllerManifest(JsonContract): ...
class ControllerManifests(JsonContract): ...
class PipelineDslSpec(JsonContract): ...
class ExecutionPlan(JsonContract): ...
class ExecutionBundle(JsonContract): ...

class FoldSet(JsonContract):
    def fingerprint(self) -> str: ...

class CompiledPipelineArtifact(JsonContract):
    @property
    def graph(self) -> GraphSpec: ...
    @property
    def campaign_template(self) -> CampaignSpec: ...

def version() -> str: ...
def contract_manifest_json() -> str: ...
def validate_graph_json(json: str) -> None: ...
def validate_campaign_json(json: str) -> None: ...
def validate_controller_manifest_json(json: str) -> None: ...
def validate_controller_manifest_list_json(json: str) -> None: ...
def validate_pipeline_dsl_json(json: str) -> None: ...
def validate_execution_plan_json(json: str) -> None: ...
def validate_execution_bundle_json(json: str) -> None: ...
def validate_fold_set_json(json: str) -> None: ...
def fold_set_fingerprint_json(json: str) -> str: ...
def compile_pipeline_dsl_graph_json(json: str) -> str: ...
def compile_pipeline_dsl_artifact_json(json: str) -> str: ...
def compile_pipeline_dsl_artifact_with_controllers_json(
    dsl_json: str, controller_manifests_json: str
) -> str: ...
def compile_pipeline_dsl_graph(dsl: Any) -> GraphSpec: ...
def compile_pipeline_dsl_artifact(dsl: Any) -> CompiledPipelineArtifact: ...
def compile_pipeline_dsl_artifact_with_controllers(
    dsl: Any,
    controller_manifests: Any,
) -> CompiledPipelineArtifact: ...
def fan_out_data_aware_branches_json(dsl_json: str, envelope_json: str) -> str: ...
def fan_out_data_aware_branches(dsl: Any, envelope: Any) -> PipelineDslSpec: ...
def build_execution_plan_json(
    plan_id: str,
    graph_json: str,
    campaign_json: str,
    controller_manifests_json: str,
) -> str: ...
def build_execution_plan(
    plan_id: str,
    graph: Any,
    campaign: Any,
    controller_manifests: Any,
) -> ExecutionPlan: ...
