from os import PathLike
from typing import Any, Self

class DagMlError(Exception):
    category: str
    code: str
    severity: str
    remediation_hint: str
    context: dict[str, Any]
    context_json: str
    descriptor_json: str

class DagMlValidationError(DagMlError): ...
class DagMlRuntimeError(DagMlError): ...
class DagMlDataError(DagMlError): ...
class DagMlControllerError(DagMlError): ...
class DagMlBundleError(DagMlError): ...
class DagMlLineageError(DagMlError): ...
class DagMlReplayError(DagMlError): ...
class DagMlSecurityError(DagMlError): ...
class DagMlCompatibilityError(DagMlError): ...
class DagMlInternalError(DagMlError): ...

__version__: str

class JsonContract:
    def __init__(self, value: Any) -> None: ...
    @classmethod
    def from_path(cls, path: str | PathLike[str]) -> Self: ...
    def json(self) -> str: ...
    def to_dict(self) -> Any: ...

class GraphSpec(JsonContract): ...
class CampaignSpec(JsonContract): ...
class ControllerManifest(JsonContract): ...
class ControllerManifests(JsonContract): ...
class HostControllerSpec(JsonContract): ...
class HostControllerSpecs(JsonContract): ...
class PipelineDslSpec(JsonContract): ...
class ExecutionPlan(JsonContract): ...
class ExecutionBundle(JsonContract): ...

class TrainingRequest(JsonContract):
    def project(self) -> TrainingContractProjection: ...

class TrainingContractProjection(JsonContract): ...
class TrainingOutcome(JsonContract): ...
class TrainingReplayRequest(JsonContract): ...
class TrainingReplayOutcome(JsonContract): ...
class ParameterProjection(JsonContract): ...
class CacheNamespace(JsonContract): ...
class PortablePredictorPackage(JsonContract): ...

class LocalImplementationRegistry:
    def __init__(self) -> None: ...
    def register_loss(self, loss_reference: Any, implementation: Any) -> None: ...
    def register_metric(self, metric_reference: Any, implementation: Any) -> None: ...
    def resolve_loss(self, loss_reference: Any) -> Any: ...
    def resolve_training_loss(self, training_loss_role: Any, phase: str) -> Any: ...
    def resolve_metric(self, metric_reference: Any) -> Any: ...
    def invoke_training_loss(
        self,
        node_task: Any,
        *args: Any,
        role_index: int = 0,
        **kwargs: Any,
    ) -> dict[str, Any]: ...
    def evaluate_metric(self, metric_task: Any) -> dict[str, Any]: ...
    def unregister_loss(self, loss_reference: Any) -> Any: ...
    def unregister_metric(self, metric_reference: Any) -> Any: ...
    def descriptors(self) -> list[dict[str, Any]]: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...

class TrainingResult:
    def __init__(self, native: Any) -> None: ...
    @property
    def is_attached(self) -> bool: ...
    @property
    def process_local_artifact_count(self) -> int | None: ...
    @property
    def process_local_data_handle_count(self) -> int | None: ...
    @property
    def process_local_data_view_count(self) -> int | None: ...
    @property
    def outcome_fingerprint(self) -> str: ...
    @property
    def outcome(self) -> TrainingOutcome: ...
    @property
    def execution_bundle(self) -> ExecutionBundle: ...
    @property
    def score_set(self) -> dict[str, Any]: ...
    @property
    def outputs(self) -> list[dict[str, Any]]: ...
    @property
    def artifacts(self) -> list[dict[str, Any]]: ...
    @property
    def portable_prediction_caches(self) -> dict[str, Any] | None: ...
    def detach(self) -> bool: ...
    def outcome_json(self) -> str: ...
    def execution_bundle_json(self) -> str: ...
    def score_set_json(self) -> str: ...
    def outputs_json(self) -> str: ...
    def artifacts_json(self) -> str: ...
    def portable_prediction_caches_json(self) -> str | None: ...
    def portable_predictor_package_json(
        self,
        package_id: str,
        *,
        fitted_artifact_mode: str = "allow_host_sidecar",
        artifact_load_mode: str = "host_sidecar",
    ) -> str: ...
    def export_portable_predictor_package(
        self,
        package_id: str,
        *,
        fitted_artifact_mode: str = "allow_host_sidecar",
        artifact_load_mode: str = "host_sidecar",
    ) -> PortablePredictorPackage: ...
    def replay_json(
        self,
        request: Any,
        data_envelopes: Any,
        *,
        outcome_id: str,
        run_id: str,
        warnings: list[str] | None = None,
        diagnostics: dict[str, Any] | None = None,
    ) -> str: ...
    def replay(
        self,
        request: Any,
        data_envelopes: Any,
        *,
        outcome_id: str,
        run_id: str,
        warnings: list[str] | None = None,
        diagnostics: dict[str, Any] | None = None,
    ) -> TrainingReplayOutcome: ...

class FoldSet(JsonContract):
    def fingerprint(self) -> str: ...

class CompiledPipelineArtifact(JsonContract):
    @property
    def graph(self) -> GraphSpec: ...
    @property
    def campaign_template(self) -> CampaignSpec: ...

def version() -> str: ...
def contract_manifest_json() -> str: ...
def validate_graph_json(json: str) -> None: ...
def validate_campaign_json(json: str) -> None: ...
def validate_controller_manifest_json(json: str) -> None: ...
def validate_controller_manifest_list_json(json: str) -> None: ...
def derive_controller_manifest_json(host_controller_spec_json: str) -> str: ...
def derive_controller_manifest_list_json(host_controller_specs_json: str) -> str: ...
def validate_pipeline_dsl_json(json: str) -> None: ...
def validate_execution_plan_json(json: str) -> None: ...
def validate_execution_bundle_json(json: str) -> None: ...
def validate_training_request_json(json: str) -> None: ...
def sign_training_request_json(json: Any) -> str: ...
def project_training_request_json(json: str) -> str: ...
def validate_training_contract_projection_json(json: str) -> None: ...
def validate_training_outcome_json(json: str) -> None: ...
def validate_training_replay_request_json(json: str) -> None: ...
def validate_training_replay_outcome_json(json: str) -> None: ...
def validate_parameter_projection_json(json: str) -> None: ...
def validate_cache_namespace_json(json: str) -> None: ...
def validate_portable_predictor_package_json(json: str) -> None: ...
def validate_fold_set_json(json: str) -> None: ...
def fold_set_fingerprint_json(json: str) -> str: ...
def sample_relation_set_fingerprint_json(json: str) -> str: ...
def loss_execution_attestation(
    training_loss_role: Any, phase: str
) -> dict[str, Any]: ...
def compile_pipeline_dsl_graph_json(json: str) -> str: ...
def compile_pipeline_dsl_artifact_json(json: str) -> str: ...
def compile_pipeline_dsl_artifact_with_controllers_json(
    dsl_json: str, controller_manifests_json: str
) -> str: ...
def compile_pipeline_dsl_graph(dsl: Any) -> GraphSpec: ...
def compile_pipeline_dsl_artifact(dsl: Any) -> CompiledPipelineArtifact: ...
def compile_pipeline_dsl_artifact_with_controllers(
    dsl: Any,
    controller_manifests: Any,
) -> CompiledPipelineArtifact: ...
def derive_controller_manifest(host_controller_spec: Any) -> ControllerManifest: ...
def derive_controller_manifests(host_controller_specs: Any) -> ControllerManifests: ...
def fan_out_data_aware_branches_json(dsl_json: str, envelope_json: str) -> str: ...
def fan_out_data_aware_branches(dsl: Any, envelope: Any) -> PipelineDslSpec: ...
def build_execution_plan_json(
    plan_id: str,
    graph_json: str,
    campaign_json: str,
    controller_manifests_json: str,
) -> str: ...
def build_execution_plan(
    plan_id: str,
    graph: Any,
    campaign: Any,
    controller_manifests: Any,
) -> ExecutionPlan: ...
def sign_training_request(request: Any) -> TrainingRequest: ...
def project_training_request(request: Any) -> TrainingContractProjection: ...
def execute_training_json(
    request_json: str,
    data_envelopes_json: str,
    relations_json: str,
    training_influence_json: str,
    op_callback: Any,
    outcome_id: str,
    run_id: str,
    bundle_id: str,
    warnings_json: str = "[]",
    diagnostics_json: str = "{}",
) -> TrainingResult: ...
def execute_training(
    request: Any,
    data_envelopes: Any,
    relations: Any,
    training_influence: Any,
    op_callback: Any,
    *,
    outcome_id: str,
    run_id: str,
    bundle_id: str,
    warnings: Any = (),
    diagnostics: Any = None,
) -> TrainingResult: ...
def replay_loaded_predictor_package_json(
    package: Any,
    request: Any,
    data_envelopes: Any,
    artifact_handles: Any,
    op_callback: Any,
    *,
    outcome_id: str,
    run_id: str,
    warnings: Any = (),
    diagnostics: Any = None,
) -> str: ...
def replay_loaded_predictor_package(
    package: Any,
    request: Any,
    data_envelopes: Any,
    artifact_handles: Any,
    op_callback: Any,
    *,
    outcome_id: str,
    run_id: str,
    warnings: Any = (),
    diagnostics: Any = None,
) -> TrainingReplayOutcome: ...
def canonical_operator_variant_label(steps_json: str) -> str: ...
